### ISSUE TITLE
vlc-qt  fullscreen mode

### ISSUE THREAD

**Issue by skullhead** [ntadej/vlc-qt#37] opened 2014-04-13 10:34 UTC
Hello everyone. I started studying vlc-qt and I have a problem. I have pasted vlcvideowidget in qwidget. Video works, but takes up only a small area in the corner of the  mainwindow. 
But I need a full-screen mode. How do I make the videoframe takes all the mainwindow? I think it should be easy, but not for such a newbie like me)
I also have the following errors:
[00000000028e98b8] main interface error: no suitable interface module
[0000000002a45dc8] main vout display error: Failed to set on top

 Here is the code
```
DemoPlayer.cpp
#include <vlc-qt/Common.h>
#include <vlc-qt/Instance.h>
#include <vlc-qt/Media.h>
#include <vlc-qt/MediaPlayer.h>
#include <vlc-qt/WidgetVideo.h>
#include "DemoPlayer.h"

#include <QtWidgets>


DemoPlayer::DemoPlayer(QWidget *parent)
    : QMainWindow(parent),
      _videowidget(0),
      _media(0)
{
    _instance = new VlcInstance(VlcCommon::args(), this);
    _media = new VlcMedia("C:/promo/repeat.mp4", true, _instance);
    _player = new VlcMediaPlayer(_instance);
    _videowidget = new VlcWidgetVideo(_player,this);
    _player->setVideoWidget(_videowidget);
    _videowidget->show();
    _player->open(_media);
    _player->play();

main.cpp
#include <QApplication>

#include "DemoPlayer.h"

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    DemoPlayer mainWindow;
    mainWindow.showfullscreen();
    return app.exec();
}


DemoPlayer.h
#ifndef DEMOPLAYER_H_
#define DEMOPLAYER_H_
#include <QMainWindow>
#include <QWidget>
class VlcInstance;
class VlcMedia;
class VlcMediaPlayer;
class VlcWidgetVideo;

class DemoPlayer : public QMainWindow
{
Q_OBJECT
public:
    explicit DemoPlayer(QWidget *parent = 0);


public:
    VlcInstance *_instance;
    VlcMedia *_media;
    VlcMediaPlayer *_player;
    VlcWidgetVideo *_videowidget;
};

#endif // DEMOPLAYER_H_
```

**Comment by ntadej** [comment] 2015-04-13 19:10
Duplicate of #21.

**Closed by ntadej** 2015-04-13 19:10 UTC
Labels: Needs feedback
